### ISSUE TITLE
Fallback for Theme Properties

### ISSUE THREAD

**Issue by BanDroid** [oarabiledev/material-design#1]
it is so hard everytime creating new app and have appTheme.json be ready, if there's 1 color missing it thrown json not valid exception which is infuriating. could you just make a fallback object if the resources file does not need to modify all of theme name?

for example, i just created a new app, and i create theme.json with `{}` empty json like this, because i dont want to modify any color at the moment, but the app would use fallback of default material3 color resources for that specific null color in theme.json.

![Screenshot_20240324-004408.png](https://github.com/oarabiledev/Material3/assets/68449470/3efc9cdb-ff88-4229-8078-1895fada330f)

**Comment by oarabiledev** [comment]
Thanks for telling me, I'll update accordingly, I advise you take the XML provided and convert it to JSON, I will add an exception to test for various color values and if they don't have assigned values it will notify in a less angry way, please tell me what I can also do..
I'm not sure if I'll be able to do so today, as it's 7:55 pm but definitely tomorrow I'll release an update. 
Regards::
Oara 🫡

**Comment by oarabilekoore** [comment]
Hey, I have added a partial fix, add defaultTheme as null, if you meet a similar error, update to v0.78.
Thanks for pointing it out : 🫡

**Comment by BanDroid** [comment]
i'll re-open this ticket because it was not fixed in my end.

edit:
i cant edit this issue status
