### ISSUE TITLE
Bug: Cannot use NodeJS together with Material3 Plugin 

### ISSUE THREAD

**Issue by BanDroid** [oarabiledev/material-design#2]
just add `cfg.Node` will throw this exception.

![Screenshot_20240324-025307.png](https://github.com/oarabiledev/Material3/assets/68449470/7aec61e1-a65c-4b20-8411-8094a8fe9818)

**Comment by oarabilekoore** [comment]
Bug has been fixed, wait for plugin update, or compile plugin raw, (Switch Material3.js and Material3.inc files with latest files)
